### ISSUE TITLE
Dash case in frontmatter key crashes MDXRemote

### ISSUE THREAD

**Issue by vincerubinetti** [hashicorp/next-mdx-remote#156] opened 2021-06-06 21:47 UTC
I have an MDX file like this:

```mdx
---
big-header: true
---

<Section>

...blah blah
```

Rendering it like this, after processing it with `gray-matter`, per the documentation:

```jsx
console.log(source); // this outputs the expected object, like { compiledSource: "...", scope: ...} 
return <main><MDXRemote {...source} components={components} /></main>
```

... causes this error:

```
Server Error
SyntaxError: Arg string terminates parameters early

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
.next\server\pages\_document.js (179:33) @ Function.getInitialProps

  177 |     }
  178 | 
> 179 |     const { html, head } = await ctx.renderPage({ enhanceApp })
      |                                 ^
  180 |     const styles = [...flush()]
  181 |     return { html, head, styles }
  182 |   }
Show collapsed frames
```

Taking out the dash in `big-header` makes it work just fine. `gray-matter` seems to output the same `data` and `content` in either case. Taking out the `<MDXRemote>` component also makes the crash go away. Thus, I think it's an issue with this library.

**Comment by jescalan** [comment] 2021-06-07 00:57
You are indeed correct - I have no idea why, but using a dash in a yaml frontmatter key will cause a cryptic error, just verified this with a test. Technically, frontmatter usage is outside the scope of this library, but it is a common use case and something we have as an example in the readme so I will try to figure out what's going on here.

**Comment by jescalan** [comment] 2021-06-07 01:10
Confirmed as a bug. In the meantime the best workaround is to not use dash case for keys in your frontmatter.

**Comment by jescalan** [comment] 2021-06-07 01:37
Ok I think I see what happened here. The issue specifically with this case is with the `scope` argument, which is an object that has a variable name as the key and a variable value as the value. There are a couple issues with the way this argument is currently documented in the readme.

Let's break down the issue. On [the line noted above](https://github.com/hashicorp/next-mdx-remote/blob/main/src/index.tsx#L82), we evaluate a string of source code into a function on the client side. This must be done in order to construct the mdx function from the serialized value returned from the `serialize` function in `getStaticProps`. In order to do so, we need to be aware of all of the variables that need to be in scope when the source code is evaluated, which includes the `scope` argument. When you put a `dash-case` key in the `scope` argument, it is treated as the name of a variable, and is evaluated as such. However, javascript variables cannot contain a dash in the name, this is a syntax error. And that is the reason why we get an error.

The way you can fix this issue is by ensuring that any key that is included in a `scope` object that you pass into `<MDXRemote>` is a valid javascript variable name. In this case, it seems likely that you are passing all your frontmatter data in as `scope` even when you do not need to be doing so. Not doing this would probably solve the issue in your case. The `scope` argument should be reserved specifically for when you are trying to pass a variable in that can be consumed by a custom component, and all keys in the `scope` argument must be valid as javascript variable names in order for it to work properly.

I'm going to close this issue - I don't think this is actually a bug with the library now, as much as a lack of clarity in the documentation. I [just put in a PR](https://github.com/hashicorp/next-mdx-remote/pull/157) to add a lot more clarity around the `scope` argument in the readme. If you want to take a moment to check it out, that would be great. Hopefully this will be helpful to anyone else who comes across this issue in the future!

**Closed by jescalan** 2021-06-07 01:37 UTC
Labels: bug
