### ISSUE TITLE
Error: Cannot find package 'next-mdx-remote' in Next.js 12 environment

### ISSUE THREAD

**Issue by nimuseel** [hashicorp/next-mdx-remote#239] opened 2022-02-21 11:58 UTC
Hi! I'm creating a personal engineering blog using `Next.js` and `next-mdx-remote` and `yarn-berry`.

But trying to render mdx using next-mdx-remote caused an error called `Error: Cannot find package 'next-mdx-remote'`.

I tried to change it to `pakcage.json>type: 'module'` and reinstall the package, but it was not resolved, so I left it as an issue.

Below is my development environment. Please refer to it. I want you to give me feedback on what I'm doing wrong.
Also, yarn-berry version is `3.1.1`.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/48236404/154950950-28547a06-127a-4207-8c12-59d497f73de8.png">

I don't know if it'll help, but I'll also attach an error message.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/48236404/154951077-ef9c3066-5709-401e-8753-1e90a163a2c9.png">

**Comment by max-pod** [comment] 2022-02-22 00:09
Sorry for the dumb question, but have you confirmed that next-mdx-remote is actually installed, ie in your yarn/npm lock and node modules folder?

**Comment by nimuseel** [comment] 2022-02-22 00:13
@max-pod 

Yes, it is well located in the yarn.lock file.

**Comment by max-pod** [comment] 2022-02-22 00:25
Could you replicate the error in a sample repo?

**Comment by nimuseel** [comment] 2022-02-26 12:34
@max-pod 

Sorry for the late reply. Test it here in the repository. 
https://github.com/nimuseel/nimuseel-next

**Comment by max-pod** [comment] 2022-03-01 22:59
@nimuseel I checked out the repo and couldn't find the error, and saw a commit titled [fix: 불필요 코드 제거](https://github.com/nimuseel/nimuseel-next/commit/2488d5509ff71b9030eb5bb4a7b2b208c90a9b89). Seems like you got it working?

**Comment by nimuseel** [comment] 2022-03-02 11:21
@max-pod 

When using the mdx-bundler, there was no error, so I avoided the error by using the mdx-bundler first. Currently, we have found an alternative plan, but we want to use next-mdx-remote.

**Comment by shmoon2917** [comment] 2022-03-04 13:20
@nimuseel I had the same problem and yarn-berry and next-mdx-remote version is same as yours. I downgraded to version 3 and It works for me🙌   

when installing the version 4, it is located in yarn's virtual folder(`__virtual__`). This is the only difference. @max-pod

**Comment by nimuseel** [comment] 2022-03-04 14:00
@shmoon2917 

Oh! I'll give it a try. Thank you.

**Comment by mohouyizme** [comment] 2022-04-21 16:18
I'm facing the same problem, I'm using:
yarn: 3.1.1
node: 17.9.0
next: 12.1.4

**Comment by jdcampolargo** [comment] 2022-09-09 03:56
run `yarn run build` and fix those errors. That fixed my problem!

**Comment by jdcampolargo** [comment] 2022-09-09 03:57
also run `yarn add @mdx-js/mdx`

**Comment by BRKalow** [comment] 2023-02-11 03:58
Hi y'all, I'm going to close this out. If you're still running into this, feel free to open a new issue with a minimal reproduction so we can investigate further. Thanks.

**Closed by BRKalow** 2023-02-11 03:58 UTC
Labels: needs replication
