### ISSUE TITLE
[support] Throws ModuleNotFoundError

### ISSUE THREAD

**Issue by lorenzode** [hashicorp/next-mdx-remote#188] opened 2021-09-13 07:49 UTC
### Issue

next-mdx-remote does not work with Nextjs, throws error

### Describe the solution you'd like

Use  next-mdx-remote in combination with Nextjs as described in https://github.com/hashicorp/next-mdx-remote

### Details

I have this situation:

Using `<MDXRemote {...contents} components={widgets} />` inside JSX in f.e. `/pages/index.js` throws error:

`ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/ld/Desktop/workspace/repos/the-influence-industry-project-website/node_modules/esbuild/lib'`.

I followed the instructions here:
https://mdxjs.com/getting-started/next

Component code:

```
import { GetStaticProps } from 'next'
import { map, compact } from 'lodash'
import { MDXRemote } from 'next-mdx-remote'

import styles from '../styles/Home.module.css'
import conf from '../configuration'
import { redirectOnHttpError, test, createMarkup, l, test2} from '../lib/utils'
import { APIData } from '../lib/types'

import widgets from '../lib/widgets'

export const Homepage: React.FC<{
  homepage: APIData,
  allCards: Array<APIData>,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  m: any
}>  = (props) => {
  const {homepage} = props
  return (
    // Global styles
    <div className="container">
      {/* Module specific styles */}
      <h1 className={styles.h1}>
        {homepage.title}
      </h1>
      <p>{test()}</p>
      <p>{test2()}</p>
      <p>{l('news', 'en')}</p>
      {
        homepage.introduction_text
          ? <section>
            <p>{homepage.introduction_text}</p>
          </section>
          : ''
      }
      <div dangerouslySetInnerHTML={createMarkup('Test')} />

      {/* {
        homepage?.sections
          ? map(homepage.sections, (section, i) =>
            section?.section?.cards
              ? <Section
                key={`section-${i}`}
                title={section.section.title}
                format={section.section.format}
                cards={
                  compact(map(allCards, c => {
                    if (section.section.cards.includes(c.uuid)) return c
                    return null
                  }))
                }
              />
              : null
          )
          : ''
      }*/}
    <MDXRemote {...m} components={widgets} />
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const homepage = await fetch(`${conf.contentApiUrlAndNamespace}?uuid=46f0415e-9bef-4b3b-993e-498a585f978f`)
  const homepageJson = await homepage.json()
  const h = await redirectOnHttpError(homepageJson)

  const m = await mdxify('**test** <AnotherTest text={"test"} />')

  return {
    props: {
      homepage: h,
      m: m
    }
  }
}

export default Homepage
```

Additional output when I run `npm run dev`:

```
./node_modules/@babel/core/lib/transformation/normalize-file.js:9:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
./node_modules/@babel/core/lib/transformation/index.js
./node_modules/@babel/core/lib/transform.js
./node_modules/@babel/core/lib/index.js
./node_modules/@mdx-js/mdx/mdx-hast-to-jsx.js
./node_modules/@mdx-js/mdx/index.js
./node_modules/next-mdx-remote/dist/serialize.js
./node_modules/next-mdx-remote/serialize.js
./lib/utils.ts
./pages/index.tsx
```

**Comment by lorenzode** [comment] 2021-09-13 10:40
For googlers:

Adding this to `next.config.js` fixed my build issue:

```
module.exports = {
  webpack5: true,
  webpack: (config) => {
    config.resolve.fallback = {
      fs: false,
      path: false,
      child_process: false,
      crypto: false,
      os: false,
      tty: false
    }

    return config
  },
}
```

However now I get this on `npm run dev`:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'split')

Call Stack
eval
node_modules/esbuild/lib/main.js (1582:30)
Object../node_modules/esbuild/lib/main.js
```

**Comment by jescalan** [comment] 2021-09-13 16:06
I'm fairly confident that this line is your issue:

```js
const m = await mdxify('**test** <AnotherTest text={"test"} />')
```

What is `mdxify`? Where does it come from? This is not how usage is documented.

**Comment by jescalan** [comment] 2021-09-13 16:08
I'm going to close this since it's an individual support issue but please feel free to continue following up here!

**Closed by jescalan** 2021-09-13 16:08 UTC
Labels: support

**Comment by lorenzode** [comment] 2021-09-13 17:37
@jescalan mdxify is just a wrapper around serialize:
```
// /libs/utils.ts
export const mdxify = async (markdownString: string) => {
  const mdxifiedString = await serialize(markdownString)
  return mdxifiedString
}
```

**Comment by jescalan** [comment] 2021-09-13 17:43
This is almost certainly the cause of the issue. Take this out of the utils file, and import serialize directly in your template. Putting any of `mdx-remote`'s piece inside a `utils` file is a common cause for error as nextjs can have issues code splitting it and include server-side code in the client bundle, which looks a lot like the error you have here.

Here's what I recommend. Start with the simplest case as prescribed in the docs and make sure that works, then make incremental changes from there and it will be easier to spot what is causing the problem.

**Comment by lorenzode** [comment] 2021-09-13 18:22
Thanks!
