### ISSUE TITLE
Support for Next v15

### ISSUE THREAD

**Issue by mellevanderlinde** [hashicorp/next-mdx-remote#481] opened 2024-10-25 15:33 UTC
### Describe the bug

`next-mdx-remote` does not work with the latest version of Next (v15.0.1). When creating a next app, the package can't be installed.

### Reproduction

```
npx create-next-app@latest # using all defaults
cd my-app
npm install next-mdx-remote
```

This results in the following error:

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: my-app@0.1.0
npm error Found: react@19.0.0-rc-69d4b800-20241021
npm error node_modules/react
npm error   react@"19.0.0-rc-69d4b800-20241021" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">=16" from next-mdx-remote@5.0.0
npm error node_modules/next-mdx-remote
npm error   next-mdx-remote@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

### next-mdx-remote version

v5.0.0

**Comment by juanpmd** [comment] 2024-11-07 15:48
I see this was marked as completed but still not working on Next.js 15.0.3 (with next-mdx-remote v5.0.0). Did someone manage to make it work?

**Comment by stephengade** [comment] 2024-11-12 23:57
@juanpmd @mellevanderlinde 

add this to your nextConfig file` transpilePackages: ['next-mdx-remote']`

it solves it for me.

**Comment by mellevanderlinde** [comment] 2024-11-15 17:46
@stephengade After adding this to next.config.ts, I still get the same error message as before

**Comment by l00sed** [comment] 2024-11-16 03:28
The issue is that Next version 15 requires React 19 RC (revision candidate) in order to use all the new features. You can still use `next-mdx-remote` if you install with `npm install --force` or override the dependencies as described in the Next 15 [upgrade guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#installing).

I'm not a fan of using a revision candidate in something marked as "stable", but I that's a personal opinion.

**Comment by bakenray** [comment] 2024-11-26 13:10
is there any man to fix this bug? Next.js V15 not work....  if i use `--force` to install it. after that, when i run `npm insall` something, i most take `--force` everytime.

**Comment by l00sed** [comment] 2024-11-26 14:07
> is there any man to fix this bug? Next.js V15 not work.... if i use `--force` to install it. after that, when i run `npm insall` something, i most take `--force` everytime.

See my comment above yours. The issue is Next.js 15 uses React 19RC (revision candidate). The Next 15 release was marked "stable", but they're using a version of React that is not ready for production. You need to use `--force` or override the dependencies (see the link above).

IMO, yes, this whole situation is dumb.

**Comment by CorneliusKluge** [comment] 2024-12-06 14:08
Ping on this: [React 19 is now stable](https://react.dev/blog/2024/12/05/react-19).

**Closed** 2024-12-17 15:34 UTC

**Comment by mellevanderlinde** [comment] 2024-12-17 15:35
The issue was solved for me by using the latest version of Next (15.1.0)
