### ISSUE TITLE
next/link links with hash not working

### ISSUE THREAD

**Issue by iAdramelk** [hashicorp/next-mdx-remote#65] opened 2020-12-02 13:37 UTC
I'm trying to render markdown docs using `mdx` and `next-mdx-remote`. I replaced standard `<a>` tags in docs with `next/link` for smoother navigation. It works, but if the link has fragment link, e. g. `docs/page#about`, then navigation to anchor on page load didn't work. If I just render `renderOutput` to `dangerouslySetInnerHTML={{ __html: mdx.renderedOutput }}`, then everything works correctly.

My guess is that bug happens because [navigation to hash](https://github.com/vercel/next.js/blob/e1737809db9a16e622e9ca7772d0a0f3d9db71d2/packages/next/next-server/lib/router/router.ts#L1157) hapens at the time then `hydrate` is replacing the page content and there are no actual anchor on the page.

**Comment by iAdramelk** [comment] 2020-12-02 13:44
P. S. Wrapping [setResult](https://github.com/hashicorp/next-mdx-remote/blob/master/hydrate.js#L60) call in additional `requestIdleCallback` fixed problem for me, but I'm not sure that it will work in 100% of cases:

```
window.requestIdleCallback(() => setResult(wrappedWithMdxProvider))
```

**Comment by helloworld** [comment] 2020-12-04 20:49
@iAdramelk where did you include that snippet?

**Comment by iAdramelk** [comment] 2020-12-07 13:25
@helloworld sorry for the late answer. At the line [60 of hydrate.js](https://github.com/hashicorp/next-mdx-remote/blob/master/hydrate.js#L60), I'm wrapping `setResult(wrappedWithMdxProvider)` in it.

**Comment by brandonpittman** [comment] 2020-12-17 01:52
Same issue here.

**Comment by maximousblk** [comment] 2020-12-23 13:50
I'm having the same problem.

I have `pages/[slug].tsx` which fetches mdx and renders the page. links in which `[slug]` is defined by me work correctly, example: on `example.com/page1` if there is a link to `[Section on Page 2](/page2#section-id)` it works fine. but if the link only has the "hash link" like [Section on This Page](#section-id)` the I get the following error:

```js
Uncaught (in promise) Error: The provided `href` (/[slug]#section-id) value is missing query values (slug) to be interpolated properly. Read more: https://err.sh/vercel/next.js/href-interpolation-failed
    at Router._callee$ (router.ts?35b8:810)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?c973:3)
    at _next (asyncToGenerator.js?c973:25)
```

**Comment by juniorRubyist** [comment] 2021-01-26 16:22
> I'm trying to render markdown docs using `mdx` and `next-mdx-remote`. I replaced standard `<a>` tags in docs with `next/link` for smoother navigation.

Just curious: did you do this by setting the `renderToString` parameter on `components` or `hydrate`?

**Comment by juniorRubyist** [comment] 2021-01-26 17:31
> > I'm trying to render markdown docs using `mdx` and `next-mdx-remote`. I replaced standard `<a>` tags in docs with `next/link` for smoother navigation.
>
> Just curious: did you do this by setting the `renderToString` parameter on `components` or `hydrate`?

nevermind. turns out it's both. I digress. :)

**Comment by jescalan** [comment] 2021-05-24 18:18
This should be resolved as of v2. Has anyone had a chance to check and confirm?

**Comment by brandonpittman** [comment] 2021-05-25 00:18
> This should be resolved as of v3. Has anyone had a chance to check and confirm?

Didn't see it mentioned in the release notes but I'll try it out! Thanks.

**Comment by jescalan** [comment] 2021-06-24 23:23
@brandonpittman just wanted to check if you could confirm here?

**Comment by brandonpittman** [comment] 2021-06-29 01:34
@jescalan I can confirm this works! Also, first time using the new API and it's lovely. ❤️

**Comment by jescalan** [comment] 2021-06-29 03:51
wonderful! thanks so much. will close this one out!

**Closed by jescalan** 2021-06-29 03:51 UTC
Labels: bug
