### ISSUE TITLE
How to type remarkPlugins and rehypePlugins (Typescript)

### ISSUE THREAD

**Issue by evantahler** [hashicorp/next-mdx-remote#86] opened 2020-12-28 18:19 UTC
I'm very excited for v2.x.x of `next-mdx-remote` and gaining Typescript support!  

Trying out v2.0.1, I cannot figure out how to properly type the `remarkPlugins` and `rehypePlugins` options for `renderToString`.

You can see how we use it for www.grouparoo.com here https://github.com/grouparoo/www.grouparoo.com/blob/master/utils/mdxUtils.ts#L19-L22

```ts
import rehypePrism from "@mapbox/rehype-prism";
import externalLinks from "remark-external-links";

export const mdxOptions = {
  remarkPlugins: [[externalLinks, { target: "_blank" }]],
  rehypePlugins: [[rehypePrism, {}]],
};
```

And then later we:

```ts
  const mdxSource = await renderToString(content, {
    components,
    scope: data,
    mdxOptions, // <--- 
  });
```

Which yields the very long error:

```
(property) mdxOptions?: {
    remarkPlugins?: unified.Attacher<[unified.Settings?], unified.Settings>[];
    rehypePlugins?: unified.Attacher<[unified.Settings?], unified.Settings>[];
    hastPlugins?: unified.Attacher<...>[];
    compilers?: unified.Compiler[];
    filepath?: string;
}
These options are passed to the MDX compiler. See the MDX docs..

Type '{ remarkPlugins: (unified.Attacher<[externalLinks.RemarkExternalLinksOptions?], unified.Settings> | { target: string; })[][]; rehypePlugins: any[][]; }' is not assignable to type '{ remarkPlugins?: Attacher<[Settings?], Settings>[]; rehypePlugins?: Attacher<[Settings?], Settings>[]; hastPlugins?: Attacher<[...?], Settings>[]; compilers?: Compiler[]; filepath?: string; }'.
  Types of property 'remarkPlugins' are incompatible.
    Type '(Attacher<[RemarkExternalLinksOptions?], Settings> | { target: string; })[][]' is not assignable to type 'Attacher<[Settings?], Settings>[]'.
      Type '(Attacher<[RemarkExternalLinksOptions?], Settings> | { target: string; })[]' is not assignable to type 'Attacher<[Settings?], Settings>'.
        Type '(Attacher<[RemarkExternalLinksOptions?], Settings> | { target: string; })[]' provides no match for the signature '(this: Processor<Settings>, settings_0?: Settings): void | Transformer'.ts(2322)
render-to-string.d.ts(30, 5): The expected type comes from property 'mdxOptions' which is declared here on type '{ components?: any; scope?: Record<string, unknown>; mdxOptions?: { remarkPlugins?: Attacher<[Settings?], Settings>[]; rehypePlugins?: Attacher<[Settings?], Settings>[]; hastPlugins?: Attacher<...>[]; compilers?: Compiler[]; filepath?: string; }; }'
```

Any hints on how to type this properly?

Thanks!

**Comment by evantahler** [comment] 2020-12-28 18:20
I should add that if I ignore the typescript error with `//@ts-ignore`, everything works fine

**Comment by jescalan** [comment] 2021-01-04 18:56
Hey @evantahler - I'll have to look into this one! It seems to be working ok with my examples of remark plugins, but that doesn't mean it works with all of them.

**Comment by aoberoi** [comment] 2021-01-10 23:28
i'm having the same issue. i believe it occurs whenever you try to specify options for a plugin using the `[plugin, options]` value instead of just `plugin`.

Seems like `Plugin[]` isn't the appropriate type to use here, but once I dig into the types for `unified` things a little confusing for me. Perhaps we actually want to use `Pluggable[]`? That type is a union which contains `PluginTuple`, which I believe describes the `[plugin, options]` value.

**Comment by jescalan** [comment] 2021-01-20 02:59
Closed by #96

**Comment by evantahler** [comment] 2021-01-25 23:38
Thanks for the update... however, the newest versions still have the same problem for me:

```
./utils/mdxUtils.ts:44:5
Type error: Type '{ remarkPlugins: (unified.Attacher<[externalLinks.RemarkExternalLinksOptions?], unified.Settings> | { target: string; })[][]; rehypePlugins: any[][]; }' is not assignable to type '{ remarkPlugins?: Pluggable<[Settings?], Settings>[]; rehypePlugins?: Pluggable<[Settings?], Settings>[]; hastPlugins?: Pluggable<...>[]; compilers?: Compiler[]; filepath?: string; }'.
  Types of property 'remarkPlugins' are incompatible.
    Type '(Attacher<[RemarkExternalLinksOptions?], Settings> | { target: string; })[][]' is not assignable to type 'Pluggable<[Settings?], Settings>[]'.
      Type '(Attacher<[RemarkExternalLinksOptions?], Settings> | { target: string; })[]' is not assignable to type 'Pluggable<[Settings?], Settings>'.
        Type '(Attacher<[RemarkExternalLinksOptions?], Settings> | { target: string; })[]' is not assignable to type '[Attacher<[Settings?], Settings>, Settings?]'.
          Target requires 1 element(s) but source may have fewer.
```

**Comment by aoberoi** [comment] 2021-01-27 18:45
i can confirm i'm also still getting type errors. looks like someone (me?) needs to actually dive into `unified`'s types in order for us to get a solution.

@jescalan can we reopen this issue?

**Comment by jescalan** [comment] 2021-02-05 23:07
Done! Sorry for the slow movement here and appreciate the offer to help!

**Comment by BRKalow** [comment] 2022-01-21 23:10
I'm going to close this out for now as the type definitions have been updated a bit with v3 earlier this year. Please feel free to reach out if you're still seeing issues, thanks!

**Closed by BRKalow** 2022-01-21 23:10 UTC
Labels: bug

**Comment by Jule-** [comment] 2022-02-09 00:07
This #96 PR is messing things up for me. Now typescript is complaining my rehype plugins are incompatible because `Plugin[]` is incompatible with `Pluggable[]`.
Do not know why this was an issue since I have used tuple plugin configuration `[plugin, options]` without typescript errors since now. Doing so seems to break all third party plugins that export `Plugin` and not `Pluggable`.
Or am I doing something wrong?

**Comment by mauroreisvieira** [comment] 2022-03-03 13:32
The same on my side ^^

**Comment by Jule-** [comment] 2022-03-03 14:19
@BRKalow, @jescalan can you confirm this is an intended behavior? If so what can we do to make things work again?
Many thanks!

**Comment by BRKalow** [comment] 2022-03-03 15:13
Can y'all share what next-mdx-remote version you're using? v4 exposes types from the underlying `@mdx-js/mdx` library, so there shouldn't be any misalignment there.

**Comment by mauroreisvieira** [comment] 2022-03-03 16:00
Yes, with version 3.0.8 I don't have issues, only with v4.

**Comment by BRKalow** [comment] 2022-03-03 16:02
If you can share a minimal reproduction in a codesandbox or a repo I'll take a look.

**Comment by Jule-** [comment] 2022-03-03 16:08
@mauroreisvieira ho yeah you are right v4 is breaking stuff, I have tried to upgrade.
```
Type error: Type 'Plugin<[], Settings>' is not assignable to type 'Pluggable<any[]>'.
  Type 'Plugin<[], Settings>' is not assignable to type 'Plugin<any[], any, any>'.
    The 'this' types of each signature are incompatible.
      Type 'Processor<void, any, void, void> | Processor<void, any, any, any> | Processor<any, any, void, void> | Processor<void, void, void, void>' is not assignable to type 'Processor<Settings>'.
        Type 'Processor<void, any, void, void>' is not assignable to type 'Processor<Settings>'.
          Types of property 'use' are incompatible.
            Types of parameters 'plugin' and 'plugin' are incompatible.
              Type 'void | Transformer' is not assignable to type 'void | Transformer<any, any>'.
                Type 'Transformer' is not assignable to type 'void | Transformer<any, any>'.
                  Type 'Transformer' is not assignable to type 'Transformer<any, any>'.
                    Types of parameters 'file' and 'file' are incompatible.
                      Property 'contents' is missing in type 'import("/path/to/project/node_modules/next-mdx-remote/node_modules/vfile/lib/index").VFile' but required in type 'import("/path/to/project/node_modules/vfile/types/index").VFile'.
```

**Comment by BRKalow** [comment] 2022-03-03 16:11
It looks like `remark-prism` might not be updated to rely on the latest remark libraries: https://github.com/sergioramos/remark-prism/issues/304

This is likely true for many third-party remark plugins. Please keep in mind v4 is a major upgrade and there were significant changes to the underlying MDX library, as well as the unified ecosystem of libraries. This isn't an issue with `next-mdx-remote` as we're just passing through the type definitions as they are defined in `@mdx-js/mdx`, the root of the issue is that some of these plugins are likely incompatible with the latest major release of remark.

**Comment by Jule-** [comment] 2022-03-03 16:15
@BRKalow oh okay. So for all community plugins like that, we need to stick with the v3 then. Thanks for the clarifications!

**Comment by mauroreisvieira** [comment] 2022-03-03 16:16
Thank you @BRKalow

**Comment by Jule-** [comment] 2022-03-05 02:47
Well I found out the old issue I had:

```shell
$ npm ls @mdx-js/mdx
├─┬ @next/mdx@12.1.0
│ └─┬ @mdx-js/loader@2.0.0
│   └── @mdx-js/mdx@2.0.0
└─┬ next-mdx-remote@3.0.8
  └── @mdx-js/mdx@1.6.22
```

I have started to try `@next/mdx` which pulls `@mdx-js/mdx@2.0.0` and conflict with the version of `next-mdx-remote@3.0.8`.
That's why I end up with fixing `"@mdx-js/loader": "^1.6.22"`:

```shell
$ npm ls @mdx-js/mdx
├─┬ @mdx-js/loader@1.6.22
│ └── @mdx-js/mdx@1.6.22
└─┬ next-mdx-remote@3.0.8
  └── @mdx-js/mdx@1.6.22 deduped
```

In conclusion, it better not use the two libs. :wink:

**Comment by nos-nart** [comment] 2022-03-15 12:20
I cope with the same issue I have dependencies installed:
```bash
 "next-mdx-remote": "3.0.2",
 "rehype-slug": "5.0.1",
```
![image](https://user-images.githubusercontent.com/37862200/158376332-9bf0a3d4-5ade-49ab-aee5-78b45c8f513b.png)

**Comment by Jule-** [comment] 2022-03-15 18:26
@nos-nart have you read my comment? Have you tried to run the command I gave you? `@mdx-js/mdx` **is** a dependency of `next-mdx-remote` so yes you have it as an indirect dependency. You should find some learning content about the `node_modules` dependency tree.
Your `require` error is not linked to this issue, please search errors on your own before asking for help, this one is pretty much covered everywhere and the message is self-explanatory.

**Comment by jescalan** [comment] 2022-03-16 20:54
Really appreciate everyone jumping in here to help out, but let's try to keep the tone friendly and welcoming please 😁

**Comment by Jule-** [comment] 2022-03-16 22:18
I apologize, I didn't mean to sound aggressive, just trying to be helpful and remind good practices IMHO in order to keep issues clear and to respect OS authors' and contributors' time. Really, no hard feelings. :wink:

**Comment by ethernal** [comment] 2023-11-01 11:40
If anyone finds this topic I have found that typing the offending code like this works:

```ts
import { Pluggable } from 'unified';
//...
mdxOptions: {
		remarkPlugins: [
			remarkGfm,
			remarkHeadingId,
			[
				remarkToc,
				{
					heading: 'Contents',
					ordered: true,
					tight: true,
					maxDepth: 3,
				},
			] as unknown as Pluggable<any[]>,
		],
		rehypePlugins: [
			rehypeSlug,
			rehypeAutolinkHeadings,
			[rehypeExternalLinks, { target: '_blank' }] as unknown as Pluggable<
				any[]
			>,
		],
	},
```

**Comment by Jervx** [comment] 2024-08-22 05:22
Oh, I'm using `content-layer` and then also added `next-mdx-remote` for rendering the AI markdown response. That's probably why on my other project which uses only `next-mdx-remote` it works fine. Which probably mean they must not co-exist on the same project.

Probably I will remove content-layer

**Comment by Jervx** [comment] 2024-08-22 06:28
> Oh, I'm using `content-layer` and then also added `next-mdx-remote` for rendering the AI markdown response. That's probably why on my other project which uses only `next-mdx-remote` it works fine. Which probably mean they must not co-exist on the same project.
> 
> Probably I will remove content-layer

Nevermind, since `content-layer` is unmaintained, switching to forked [content-layer2](https://github.com/timlrx/contentlayer2) solves my problem

**Comment by Jervx** [comment] 2024-08-22 06:29
> Oh, I'm using `content-layer` and then also added `next-mdx-remote` for rendering the AI markdown response. That's probably why on my other project which uses only `next-mdx-remote` it works fine. Which probably mean they must not co-exist on the same project.
> 
> Probably I will remove content-layer

Nevermind, since `contentlayer` is unmaintained, switching to forked [contentlayer2](https://github.com/timlrx/contentlayer2) solves my problem
