### ISSUE TITLE
Export `renderToString()` and `hydrate()` as members of next-mdx-remote

### ISSUE THREAD

**Issue by brianespinosa** [hashicorp/next-mdx-remote#24] opened 2020-08-24 15:36 UTC
Today, we have to declare two separate import statements to get the `renderToString` and `hydrate` functions like so:

```javascript
import renderToString from 'next-mdx-remote/render-to-string'
import hydrate from 'next-mdx-remote/hydrate'
```

It would be great if we could just import members from `next-mdx-remote` instead like this:

```javascript
import { hydrate, renderToString } from 'next-mdx-remote'
```

Additionally, in `package.json` there is already a `"main": "index.js"` parameter declared, but no index.js file! So we could essentially just add an index.js file and export these members from that file and the above would just work. 

With semver this should not be a breaking change since anyone who has the individual imports declared in their code should not need to make any changes as those files are not being moved anywhere.

This is a pretty low effort update to make with adding an index.js file and updating the docs a little. I can go ahead and make a PR for this today. If there is a good reason not to do this, feel free to decline the PR. It is not going to take a lot of time.

**Comment by jescalan** [comment] 2020-08-24 20:47
Hi @brianespinosa! So, I separated them in this way on purpose to make it more reliable for nextjs to split and remove the `renderToString` function and guarantee that it's not included in the client bundle. There are some situations in which two exports out of the same file do not get properly split out and you can end up shipping a gigantic chunk of code intended only to be run at build time to the client side. I'm not quite confident enough that next's code removal will consistently correctly handle splitting out of the same file.

If you run some tests on a version that does them both, and there's no difference in bundle size at all, that would be a more compelling argument, but I'm not sure even that would be enough to fully convince me. Untangling dependencies that exist and interact together within a single file is a complex and difficult process, further complicated by the fact that any imported third party code cannot be eliminated simply because its export is unused, as it could have top-level side effects. So even if it does properly eliminate unused code for the client bundle _now_, that does not guarantee that it will indefinitely, as this library and nextjs change and evolve their codebases.

Really the thing that would convince me to accept this would be a test in the suite that ensures that none of the `renderToString` code is shipped as part of the client bundle, which would give me peace of mind that we can maintain this split properly, but that test would be fairly difficult to design. If you're willing to do this, that would be amazing though, because I do agree that the developer interface would see an improvement as a result.

**Comment by jescalan** [comment] 2020-08-28 14:23
I just double checked this with the nextjs team and they confirmed that the above is accurate and that split exports are recommended. Closing this issue but thank you for the thoughtful recommendation!

**Closed by jescalan** 2020-08-28 14:23 UTC
Labels: feature request
