### ISSUE TITLE
Why is rendered output wrapped in a <span>?

### ISSUE THREAD

**Issue by chunfeilung** [hashicorp/next-mdx-remote#30] opened 2020-08-27 21:21 UTC
First of all, thanks for making `next-mdx-remote`; this makes my life so much easier!

One thing I did notice is that `hydrate.js` wraps the `renderedOutput` in a `span` element:

```js
React.createElement('span', {
  dangerouslySetInnerHTML: {
    __html: renderedOutput,
  },
})
```

Because the `renderedOutput` may include block-level elements – which are technically not allowed within inline elements like `span` – the resulting HTML will often be invalid. As far as I can tell this does not cause any actual issues, but it does make me wonder whether this is a bug or a feature. 😄

**Comment by jescalan** [comment] 2020-08-27 22:44
Good question! It has to be rendered into something, and [we can't render it into a fragment](https://github.com/facebook/react/issues/12014), so it was just an arbitrary choice. I would be fine with changing it to a div, but that could also cause problems if your content was intended to be inline, was the theory. Although with an mdx file, I'm not even sure if its possible to generate inline content, so maybe a div is the better choice?

I'd welcome a PR either way!

**Comment by domitriusclark** [comment] 2020-09-08 13:34
Yeah I think this will cause constant bloated error messages around `dangerouslySetInnerHTML` not "matching"

Dug around a bit and it seems to need a div 🤷‍♂️ 

Can put up a PR for this if we want?

**Comment by domitriusclark** [comment] 2020-09-08 13:36
Just saw there already is a PR 😅

**Comment by stevenmunro** [comment] 2020-09-20 23:53
I recommend that this <span> or <div> (when it eventually becomes one) is **not** automatically removed using Javascript. When applying styles to markdown using a parent .markdown class, I rather the styles got applied even when Javascript is disabled.

**Comment by jescalan** [comment] 2020-11-11 16:23
Closed by https://github.com/hashicorp/next-mdx-remote/pull/34

**Closed by jescalan** 2020-11-11 16:23 UTC
