### ISSUE TITLE
Question: Consuming an existing MDXProvider

### ISSUE THREAD

**Issue by joe-bell** [hashicorp/next-mdx-remote#32] opened 2020-08-30 11:07 UTC
> Possibly related to #10 and #9

I've been following the [`next-mdx-remote` example in Next.js repo](https://github.com/vercel/next.js/pull/16613/files) and have managed to successfully migrate my `next-mdx-enhanced` implementation content and rehypePlugins, **but** I'm really struggling to get it working with my existing `MDXProvider`

I'm using Theme-UI's ThemeProvider, which means a lot of my MDX components are consuming from the Theme Provider (which is nested inside this provider). Should I be passing something into `scope` to ensure my components are referencing my MDXProvider (and its nested ThemePovider)?

Would really appreciate any support on this!

**Comment by jescalan** [comment] 2020-08-30 12:51
I think this should be resolved by #10 - I will prioritize getting that shipped out this week!

**Comment by joe-bell** [comment] 2020-08-30 16:39
Awesome thanks @jescalan, once it's in I'll test in my project and keep you posted!

**Comment by muco-rolle** [comment] 2020-10-17 09:31
Hello @joe-bell can you please share with me how you migrated from next-mdx-enhanced to next-mdx-remote I'm struggling with the plugins API and MDXProvider

**Comment by joe-bell** [comment] 2020-10-17 17:56
Hey @muco-rolle, unfortunately I'm in the same boat as you: I'm stuck on the `MDXProvider`

**Comment by jescalan** [comment] 2020-10-19 15:25
If you put up a minimal reproduction somewhere @muco-rolle I can take a look and help or let you know if additional features are required

**Comment by fr3fou** [comment] 2020-11-17 12:50
Should this be closed?

**Comment by jescalan** [comment] 2020-11-18 16:57
No, because #10 is not merged

**Comment by cadbox1** [comment] 2020-11-26 01:07
@mattboon suggested to put the ThemeProvider in the wrapper component in https://github.com/hashicorp/next-mdx-remote/pull/35#issuecomment-727171743 and I think that solves the issue for me. 

I was able to use theme-ui to style markdown without an unstyled flash: https://github.com/cadbox1/cadell-nextjs-blog-starter

**Closed** 2021-01-06 19:29 UTC
Labels: feature request
