### ISSUE TITLE
Bug: MDX syntax to JavaScript

### ISSUE THREAD

**Issue by willin** [hashicorp/next-mdx-remote#319] opened 2022-12-06 15:57 UTC
Basic Example from: <https://mdxjs.com/docs/using-mdx/>

Mdx Source:

```mdx
export const Thing = () => <>World</>

# Hello <Thing />
```

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1890238/205960500-b1dc4961-b851-4e89-9a7f-e988ccd81580.png">

**Comment by BRKalow** [comment] 2022-12-06 16:14
Duplicate of https://github.com/hashicorp/next-mdx-remote/issues/227

**Closed by BRKalow** 2022-12-06 16:14 UTC
